services:
  - type: web
    name: superkraft
    env: static
    rootDir: frontend-nextjs
    buildCommand: npm install && npm run build
    staticPublishPath: out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
